version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: NestJSAPI
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres
    container_name: NestJSDB
    restart: always
    ports:
      - 5450:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
